        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 05 01:26:35 2010
        MODULE CF_GLOBAL_SEARCH_mod
          INTERFACE 
            SUBROUTINE CF_GLOBAL_SEARCH
            END SUBROUTINE CF_GLOBAL_SEARCH
          END INTERFACE 
        END MODULE CF_GLOBAL_SEARCH_mod
