        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 05 01:26:31 2010
        MODULE GR_MAX_LSP_mod
          INTERFACE 
            SUBROUTINE GR_MAX_LSP(POINT,B_RANGE)
              COMPLEX(KIND=8) :: POINT
              COMPLEX(KIND=8) :: B_RANGE
            END SUBROUTINE GR_MAX_LSP
          END INTERFACE 
        END MODULE GR_MAX_LSP_mod
