        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 05 01:26:31 2010
        MODULE HADSI_mod
          INTERFACE 
            SUBROUTINE HADSI
            END SUBROUTINE HADSI
          END INTERFACE 
        END MODULE HADSI_mod
