        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 05 01:26:31 2010
        MODULE LHADY_mod
          INTERFACE 
            SUBROUTINE LHADY
            END SUBROUTINE LHADY
          END INTERFACE 
        END MODULE LHADY_mod
