        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 05 01:26:34 2010
        MODULE LSP_MAX_REC_mod
          INTERFACE 
            RECURSIVE SUBROUTINE LSP_MAX_REC(POINT_INIT,B_RANGE_INIT)
              COMPLEX(KIND=8), INTENT(IN) :: POINT_INIT
              COMPLEX(KIND=8), INTENT(IN) :: B_RANGE_INIT
            END SUBROUTINE LSP_MAX_REC
          END INTERFACE 
        END MODULE LSP_MAX_REC_mod
