        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 05 01:26:32 2010
        MODULE LSP_MAX_mod
          INTERFACE 
            SUBROUTINE LSP_MAX
            END SUBROUTINE LSP_MAX
          END INTERFACE 
        END MODULE LSP_MAX_mod
