        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 05 01:26:35 2010
        MODULE MACK_GLOBAL_TIME_mod
          INTERFACE 
            SUBROUTINE MACK_GLOBAL_TIME
            END SUBROUTINE MACK_GLOBAL_TIME
          END INTERFACE 
        END MODULE MACK_GLOBAL_TIME_mod
