        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 05 01:26:35 2010
        MODULE MACK_GLOBAL_SPATIAL_mod
          INTERFACE 
            SUBROUTINE MACK_GLOBAL_SPATIAL
            END SUBROUTINE MACK_GLOBAL_SPATIAL
          END INTERFACE 
        END MODULE MACK_GLOBAL_SPATIAL_mod
