        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 05 01:26:35 2010
        MODULE TS_GLOBAL_TIME_mod
          INTERFACE 
            SUBROUTINE TS_GLOBAL_TIME
            END SUBROUTINE TS_GLOBAL_TIME
          END INTERFACE 
        END MODULE TS_GLOBAL_TIME_mod
