        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 05 01:26:37 2010
        MODULE TS_SEARCH_DIFF_MODES_mod
          INTERFACE 
            SUBROUTINE TS_SEARCH_DIFF_MODES(A_TIME,B_TIME,W_TIME_INIT)
              COMPLEX(KIND=8), INTENT(IN) :: A_TIME
              COMPLEX(KIND=8), INTENT(IN) :: B_TIME
              COMPLEX(KIND=8), INTENT(IN) :: W_TIME_INIT
            END SUBROUTINE TS_SEARCH_DIFF_MODES
          END INTERFACE 
        END MODULE TS_SEARCH_DIFF_MODES_mod
