        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 05 01:26:37 2010
        MODULE TS_TRANS_TO_SPATIAL_mod
          INTERFACE 
            SUBROUTINE TS_TRANS_TO_SPATIAL(A_SPAT,B_SPAT,W_SPAT)
              COMPLEX(KIND=8), INTENT(INOUT) :: A_SPAT
              COMPLEX(KIND=8), INTENT(INOUT) :: B_SPAT
              COMPLEX(KIND=8), INTENT(INOUT) :: W_SPAT
            END SUBROUTINE TS_TRANS_TO_SPATIAL
          END INTERFACE 
        END MODULE TS_TRANS_TO_SPATIAL_mod
