        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 05 01:26:37 2010
        MODULE TS_WMAX_TIME_STAT_mod
          INTERFACE 
            SUBROUTINE TS_WMAX_TIME_STAT
            END SUBROUTINE TS_WMAX_TIME_STAT
          END INTERFACE 
        END MODULE TS_WMAX_TIME_STAT_mod
