        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 05 01:26:37 2010
        MODULE TS_WMAX_TIME_ALL_mod
          INTERFACE 
            SUBROUTINE TS_WMAX_TIME_ALL
            END SUBROUTINE TS_WMAX_TIME_ALL
          END INTERFACE 
        END MODULE TS_WMAX_TIME_ALL_mod
