        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 05 00:20:03 2010
        MODULE PROCESS_DIRECT_mod
          INTERFACE 
            SUBROUTINE PROCESS_DIRECT
            END SUBROUTINE PROCESS_DIRECT
          END INTERFACE 
        END MODULE PROCESS_DIRECT_mod
