        !COMPILER-GENERATED INTERFACE MODULE: Sat Sep 04 23:50:23 2010
        MODULE TRIM_STRING_mod
          INTERFACE 
            FUNCTION TRIM_STRING(ST) RESULT(TRIM_STRING_0)
              CHARACTER(*) :: ST
              CHARACTER(*) :: TRIM_STRING
            END FUNCTION TRIM_STRING
          END INTERFACE 
        END MODULE TRIM_STRING_mod
