        !COMPILER-GENERATED INTERFACE MODULE: Tue May 29 15:20:08 2012
        MODULE PROCESS_DIRECT__genmod
          INTERFACE 
            SUBROUTINE PROCESS_DIRECT
            END SUBROUTINE PROCESS_DIRECT
          END INTERFACE 
        END MODULE PROCESS_DIRECT__genmod
