        !COMPILER-GENERATED INTERFACE MODULE: Wed May 16 11:52:51 2012
        MODULE PROCESS_DIRECT__genmod
          INTERFACE 
            SUBROUTINE PROCESS_DIRECT
            END SUBROUTINE PROCESS_DIRECT
          END INTERFACE 
        END MODULE PROCESS_DIRECT__genmod
