        !COMPILER-GENERATED INTERFACE MODULE: Thu Mar 29 17:07:22 2012
        MODULE PROCESS_DIRECT__genmod
          INTERFACE 
            SUBROUTINE PROCESS_DIRECT
            END SUBROUTINE PROCESS_DIRECT
          END INTERFACE 
        END MODULE PROCESS_DIRECT__genmod
